/* eslint-disable */
// AUTO-GENERATED by scripts/gen-logs-types.mjs
// Source CSV : /Users/chibakenichi/卒論/Supabase Snippet ユーザープロフィール・家計管理とクイズ管理スキーマ (11).csv
// Generated   : 2025-10-06T02:54:37.399Z

export const LOGS_TABLE = 'logs' as const;

export type LogsRow = {
  "id": number;
  "profile_id": string | null;
  "occurred_at": string | null;
  "category": string | null;
  "amount": number;
  "memo": string | null;
  "is_income": boolean | null;
  "created_at": string | null;
  "ymd": string | null;
  "category_id": string | null;
  "kind": string | null;
  "yyyymm": string | null;
};

export type LogsInsert = {
  "id"?: number;
  "profile_id"?: string;
  "date"?: string;
  "category"?: string;
  "amount"?: number;
  "memo"?: string;
  "is_income"?: boolean;
  "created_at"?: string;
  "ymd"?: string;
  "category_id"?: string;
  "kind"?: string;
  "yyyymm"?: string;
};

export type LogsUpdate = {
  "id"?: number | null;
  "profile_id"?: string | null;
  "date"?: string | null;
  "category"?: string | null;
  "amount"?: number | null;
  "memo"?: string | null;
  "is_income"?: boolean | null;
  "created_at"?: string | null;
  "ymd"?: string | null;
  "category_id"?: string | null;
  "kind"?: string | null;
  "yyyymm"?: string | null;
};

// Column meta (optional helper)
export const LogsColumns = [
  { name: "id", dataType: "bigint", nullable: false, hasDefault: true },
  { name: "profile_id", dataType: "uuid", nullable: true, hasDefault: true },
  { name: "date", dataType: "date", nullable: true, hasDefault: true },
  { name: "category", dataType: "text", nullable: true, hasDefault: true },
  { name: "amount", dataType: "integer", nullable: false, hasDefault: true },
  { name: "memo", dataType: "text", nullable: true, hasDefault: true },
  { name: "is_income", dataType: "boolean", nullable: true, hasDefault: true },
  { name: "created_at", dataType: "timestamp with time zone", nullable: true, hasDefault: true },
  { name: "ymd", dataType: "date", nullable: true, hasDefault: true },
  { name: "category_id", dataType: "uuid", nullable: true, hasDefault: true },
  { name: "kind", dataType: "text", nullable: true, hasDefault: true },
  { name: "yyyymm", dataType: "text", nullable: true, hasDefault: true }
] as const;
